globalVariables(c("STATE", "MONTH", "year"))

#' Make a file name with year
#'
#' Returns a file name "accident_year.csv.bz2" with year is specified by a
#' user (using the \code{year} argument).
#'
#' @param year A specific year
#'
#' @return This function returns a string of file name.
#'
make_filename <- function(year) {
        year <- as.integer(year)
        #sprintf("accident_%d.csv.bz2", year)
        system.file("extdata", sprintf("accident_%d.csv.bz2", year), package = "Week4")
}

#' Read data
#'
#' This function reads csv data file if it exists and returns as a data frame.
#' If not, it shows an error message.
#'
#' @param filename The name of file to read.
#'
#' @return The data is returned as a data frame.
#'
#' @importFrom readr read_csv
#'
#' @importFrom dplyr tbl_df
#'
fars_read <- function(filename) {
        if(!file.exists(filename))
                stop("file '", filename, "' does not exist")
        data <- suppressMessages({
                readr::read_csv(filename, progress = FALSE)
        })
        dplyr::tbl_df(data)
}



#' Read fars_data based on years
#'
#' Returns data of specific years from US National Highway Traffic Safety
#' Administration's Fatality Analysis Reporting System.
#'
#' @param years Years to read in a vector of numbers.
#'
#' @return This function returns a list of data. The each element of the list
#' is the data from "accident_(year).csv.bz2". The file name to read is
#' generated by make_filename function and read by fars_read function.
#' If the year specified by the user does not have a file, this function
#' gives a "invalid year:" warning and returns NULL.
#'
#' @importFrom dplyr mutate select
#'
#' @importFrom magrittr %>%
#'
fars_read_years <- function(years) {
        lapply(years, function(year) {
                file <- make_filename(year)
                tryCatch({
                        dat <- fars_read(file)
                        dplyr::mutate(dat, year = year) %>%
                                dplyr::select(MONTH, year)
                }, error = function(e) {
                        warning("invalid year: ", year)
                        return(NULL)
                })
        })
}
#' Summarize fars_data by year
#'
#' This function returns a data frame which has months in row, years in
#' column, and the number of corresponding accidents number as the value of the data frame.
#'
#' @param years The years to be read.
#'
#' @return This function returns a data frame which shows the number of accidents in each month and year.
#'
#' @importFrom dplyr bind_rows group_by summarize n
#'
#' @importFrom tidyr spread
#'
#' @examples
#'fars_summarize_years(2013)
#'fars_summarize_years(2013:2015)
#'
#'@export
fars_summarize_years <- function(years) {
        dat_list <- fars_read_years(years)
        dplyr::bind_rows(dat_list) %>%
                dplyr::group_by(year, MONTH) %>%
                dplyr::summarize(n = n()) %>%
                tidyr::spread(year, n)
}

#' Map the accidents by state and year
#'
#' This function plots the position of accidents in a map with corresponding year and state from user input.
#'
#'@param state.num The state code. If it does not match the state code, the function shows "invalid STATE number:" message.
#'@param year The selected year to be studied.
#'
#'@return Returns a map shows the position of accidents.
#'
#'@importFrom dplyr filter
#'
#'@importFrom maps map
#'
#'@importFrom graphics points
#'
#'@examples
#'fars_map_state(01, 2013)
#'
#'@export
fars_map_state <- function(state.num, year) {
        filename <- make_filename(year)
        data <- fars_read(filename)
        state.num <- as.integer(state.num)

        if(!(state.num %in% unique(data$STATE)))
                stop("invalid STATE number: ", state.num)
        data.sub <- dplyr::filter(data, STATE == state.num)
        if(nrow(data.sub) == 0L) {
                message("no accidents to plot")
                return(invisible(NULL))
        }
        is.na(data.sub$LONGITUD) <- data.sub$LONGITUD > 900
        is.na(data.sub$LATITUDE) <- data.sub$LATITUDE > 90
        with(data.sub, {
                maps::map("state", ylim = range(LATITUDE, na.rm = TRUE),
                          xlim = range(LONGITUD, na.rm = TRUE))
                graphics::points(LONGITUD, LATITUDE, pch = 46)
        })
}
